[package]
name = "system76-scheduler-niri"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dbus = { version = "0.9", features = ["vendored"] }
ino_tracing = "1.0.0"
niri-ipc.workspace = true
rootcause.workspace = true
tracing = "0.1"

[lints]
workspace = true
