---
keys:
    - &me "age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6"
    - &joar "age1j0e09hj4w5u228jee09a3e8wq0x3g8nmchfmfgwvk00m8u3w8uzskynfjw"

creation_rules:
    - key_groups:
        - age:
            - *me
            - *joar
