---
keys:
  - &me age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
  - &laptop age1asg3ttsf3h4ny79va3etjdwg692aepuysptc99e7hcgdexdc8cxq8kr07l
  - &dualka age1q9vt54yjfxxn2ju7qchrnr9t7nzyuvc6k2n0s83lrkr24qdgcehqs4yp2n

creation_rules:
  - key_groups:
    - age:
      - *me
      - *laptop
      - *dualka
