"""Generate a Nix attrset from a Linux kernel .config file.

The output matches the config attrset exposed by nixpkgs kernels: keys retain
the CONFIG_ prefix and values are strings. Disabled options are omitted because
absence has the same meaning to kernel.config.isDisabled.

Usage:
    cachyos-gen-config CONFIG [-o OUTPUT]
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys

HEADER = (
    "# Generated by cachyos-gen-config (packages/cachyos/gen-config.py).\n"
    "# DO NOT EDIT.\n"
)

_SET_RE = re.compile(r"^(?P<key>CONFIG_[A-Za-z0-9_]+)=(?P<value>.*)$")


def nix_string(value: str) -> str:
    """Render a value as a Nix double-quoted string."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def parse_config(text: str) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    seen: set[str] = set()

    for line_number, line in enumerate(text.splitlines(), start=1):
        if not line or line.startswith("#"):
            continue

        match = _SET_RE.fullmatch(line)
        if match is None:
            raise ValueError(f"unrecognized line {line_number}: {line!r}")

        key = match.group("key")
        if key in seen:
            raise ValueError(f"duplicate option on line {line_number}: {key}")

        seen.add(key)
        entries.append((key, match.group("value")))

    return entries


def render(entries: list[tuple[str, str]]) -> str:
    lines = [HEADER, "{"]
    lines.extend(
        f"    {nix_string(key)} = {nix_string(value)};"
        for key, value in entries
    )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", help="kernel .config path, or - for stdin")
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="output path (default: stdout)",
    )
    args = parser.parse_args(argv)

    try:
        if args.config == "-":
            raw = sys.stdin.buffer.read()
        else:
            raw = Path(args.config).read_bytes()

        entries = parse_config(raw.decode("utf-8"))
        rendered = render(entries)

        if args.output == "-":
            sys.stdout.write(rendered)
        else:
            Path(args.output).write_text(rendered, encoding="utf-8")
    except (OSError, UnicodeError, ValueError) as error:
        print(f"gen-config: {error}", file=sys.stderr)
        return 1

    digest = hashlib.sha256(raw).hexdigest()
    print(
        f"gen-config: {len(entries)} options -> {args.output}",
        file=sys.stderr,
    )
    print(f"gen-config: input .config sha256 = {digest}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
