# Generated by `ci-driver cachyos update`.
# DO NOT EDIT.
let

    pname = "linux-cachyos";
    version = "7.2.3";
    packageVersion = "7.2.3-1";

    architecture = "x86_64_v3";
    repository = "cachyos-v3";
    baseUrl = "https://cdn77.cachyos.org/repo/${architecture}/${repository}";

    package = packageName: hash: {
        inherit packageName hash;
        url = "${baseUrl}/${packageName}-${packageVersion}-${architecture}.pkg.tar.zst";
    };

in {

    inherit pname version packageVersion architecture;

    # `uname -r` and the module-tree directory. This comes from the package
    # contents; it must not be reconstructed from the package version.
    modDirVersion = "7.2.3-1-cachyos";

    kernel = package pname
        "sha256-MHUnmPwi6jZ0vprN6WX2MVOnOb2TZTmYspyQWYkx234=";

    headers = package "${pname}-headers"
        "sha256-SeO/DghTVEasCNICwhoT0Reo+MUWBrswki6HXfpww1Q=";

    # sha256 of usr/lib/modules/<version>/build/.config in `headers`.
    configHash = "588678b97e11e00df5c02aaa151d5087b4e928f7b4b571fc7bd28ec9870d3a10";

    isLTS = false;
    isZen = false;

}
