vo = gpu-next
# hwdec = vulkan
gpu-context = auto
hdr-compute-peak = no
cache = yes

deband = no

# window-maximized=yes
hr-seek = yes
force-seekable=yes

volume=90
replaygain=album
audio-file-auto = exact

save-position-on-quit = yes
watch-later-dir = /dev/shm/mpv_watch_later
resume-playback = yes
resume-playback-check-mtime = yes

sub-visibility = no
prefetch-playlist = yes

script = /etc/profiles/per-user/teapot/share/mpv/scripts/mpris.so
