use std::collections::HashSet;
use std::str;

use anyhow::Context as _;
use anyhow::Result;
use anyhow::ensure;

const HEADER: &str = "# Generated by `ci-driver cachyos gen-config`.\n\
                      # DO NOT EDIT.\n";

#[derive(Debug)]
struct ConfigEntry {
    name: String,
    value: String,
}

/// The enabled and explicitly-valued entries from a Linux kernel `.config`.
///
/// Disabled comment entries are deliberately absent: that matches the
/// semantics of nixpkgs' `kernel.config.isDisabled` helper.
#[derive(Debug)]
pub struct KernelConfig {
    entries: Vec<ConfigEntry>,
}

impl KernelConfig {
    pub fn parse(raw: &[u8]) -> Result<Self> {
        let text = str::from_utf8(raw)
            .context("Kernel config is not valid UTF-8")?;
        let mut entries = Vec::new();
        let mut seen = HashSet::new();

        for (index, line) in text.lines().enumerate() {
            let line_number = index + 1;
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let (name, value) = line.split_once('=').with_context(|| {
                format!("Unrecognized kernel config line {line_number}: {line:?}")
            })?;
            ensure!(
                is_option_name(name),
                "Invalid kernel option on line {line_number}: {name:?}"
            );
            ensure!(
                seen.insert(name),
                "Duplicate kernel option on line {line_number}: {name}"
            );

            entries.push(ConfigEntry {
                name: name.to_owned(),
                value: value.to_owned(),
            });
        }

        Ok(Self { entries })
    }

    #[inline]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn render_nix(&self) -> String {
        let mut output = String::with_capacity(
            HEADER.len()
                + self
                    .entries
                    .iter()
                    .map(|entry| entry.name.len() + entry.value.len() + 16)
                    .sum::<usize>(),
        );
        output.push_str(HEADER);
        output.push_str("\n{\n");

        for entry in &self.entries {
            output.push_str("    ");
            push_nix_string(&mut output, &entry.name);
            output.push_str(" = ");
            push_nix_string(&mut output, &entry.value);
            output.push_str(";\n");
        }

        output.push_str("}\n");
        output
    }
}

fn is_option_name(name: &str) -> bool {
    name.strip_prefix("CONFIG_").is_some_and(|suffix| {
        !suffix.is_empty()
            && suffix
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    })
}

fn push_nix_string(output: &mut String, value: &str) {
    output.push('"');
    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '$' => output.push_str("\\$"),
            '\t' => output.push_str("\\t"),
            '\r' => output.push_str("\\r"),
            '\n' => output.push_str("\\n"),
            character => output.push(character),
        }
    }
    output.push('"');
}

#[cfg(test)]
#[expect(clippy::unwrap_used, reason = "Tests")]
mod tests {
    use super::KernelConfig;

    #[test]
    fn parses_kernel_config_semantics() {
        let config = KernelConfig::parse(
            b"# generated\n\
              CONFIG_MODULES=y\n\
              # CONFIG_UNUSED is not set\n\
              CONFIG_EXPLICITLY_DISABLED=n\n\
              CONFIG_COMMAND=\"echo ${HOME} \\\\ ok\"\n",
        )
        .unwrap();

        assert_eq!(config.len(), 3);
        assert_eq!(
            config.render_nix(),
            concat!(
                "# Generated by `ci-driver cachyos gen-config`.\n",
                "# DO NOT EDIT.\n",
                "\n",
                "{\n",
                "    \"CONFIG_MODULES\" = \"y\";\n",
                "    \"CONFIG_EXPLICITLY_DISABLED\" = \"n\";\n",
                "    \"CONFIG_COMMAND\" = \"\\\"echo \\${HOME} \\\\\\\\ ok\\\"\";\n",
                "}\n",
            )
        );
    }

    #[test]
    fn rejects_duplicate_options() {
        let error =
            KernelConfig::parse(b"CONFIG_MODULES=y\nCONFIG_MODULES=m\n")
                .unwrap_err();

        assert!(
            error
                .to_string()
                .contains("Duplicate kernel option on line 2")
        );
    }

    #[test]
    fn rejects_malformed_lines() {
        let error =
            KernelConfig::parse(b"CONFIG_MODULES y\n").unwrap_err();

        assert!(
            error
                .to_string()
                .contains("Unrecognized kernel config line 1")
        );
    }
}
