rclone_config: ENC[AES256_GCM,data:2goZqxar/zvHMEgrJI2x89v5uB1G09xDiSd14xKHwxgavEGvBFCg0styanApI7Lx1/LcO061OeePZlrWkipuMyWpOWDPFmqD3V8i4q8cGyLA47e3XFIG3PKK4iglg13HPKbjf4MVQuM3BC2TL2/yM1qlxeEI19AxJRMF0ywN0OKghVSGVsYc1l8WFbSAeo/HkHnG6bZiGjdeq5JLaafUpwhCRMhj+8zLgIFB7WKRQtqjIZHnehYy4QxQblwS5Xc4jBhiR3AJJkZmnb777Xw43eygjaL7chKbsnP1b+oEB9CaUnx4dvPDagpoHQ3AT5jL06yS+JNamhVMARcV7HFJ7iwao89rPzkq29foeTreME5e/GMSAoOEM6GPstOD/u3eJUJC2OsK4qpOzdDEn8OL+uyoJ3wwZpsOtWROfBw+pDNMB05hrzMMDxM057UnWECXciEFXSuPIKLxwKhf,iv:1ae9Ad8jWhe6cjCUzMZiOjwNaCps7qxbi6hxGYK2al8=,tag:InOZSDq8kwyz5PCWdNU65A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z1dvSHhoTWtQRENQRlRT
            cUo3VmxiTlgreThEQlJlMXdQTFFXakZRdjEwCkhUQ2dKVSs0cWZaWmdERklWRm04
            ODRaS1lBTndRMkVwVmU5bnBFOVFBV2sKLS0tIFIxRlRkT2VoOVdTaExNbFlxaUdU
            T0xqcUxEaDBPTk4ySEYzZVJlUVVBT2sKLrH1a98il34YZK+ugO2vaXPYhraEei3H
            YWVcbhmgoc2j0uoSlUIeisXGfNdzf9G8SL3CoAXGbg3k8JjovrZkDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1asg3ttsf3h4ny79va3etjdwg692aepuysptc99e7hcgdexdc8cxq8kr07l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb2NFRTQ0YUdFSDFGWm1Y
            ZlpmNGZVM0xTRzNoVzdhbTllYXBFWjc3bndrCmhnVy9ubGpFa3Z4a3R1TndkNUxL
            OVdlTEZPaXlTWmF5czJBWGkrY05jTFkKLS0tIGJjSDdUM0ZCOGpCSnZ1M3IzMmJM
            MjRncWhGUG5VRVZDcHpSZlJqSXlnTnMKKfda1bGmpjfX6L3mVrwDeCkCKIP4mM5+
            2qMts/rfyIYWIM0jgq7bIqvf0vhS1NJS3Gds9aEEurRvSf4yjQzcvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q9vt54yjfxxn2ju7qchrnr9t7nzyuvc6k2n0s83lrkr24qdgcehqs4yp2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOG1tSE83ZElrTURGV0sr
            V1dicnYzZVBHMTRlMXV5c2sxbVBWOHN1WFJZCldxeHlOUU1UZVRDUWdNNHhUUEZj
            NTc1RmxUVngxS1pHSEYxLzN4cHpYYkkKLS0tIGJKUGtGRlJaL1pkTWVmVW8wNlUz
            QzJ3UmhvL3dLdCt2TmMzdG51RXVvTEkKRp4KdndoDtOnXof1gfzJ26H/HxVSDICt
            jsatinRuCUj41QXBcqAmFKpmX7dQ+nfMQX1OZBzmcVFqfP32ZnzRZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T03:12:04Z"
    mac: ENC[AES256_GCM,data:T04+6ixAhtzgvNJNxrBFNOv6mOAxSo29+13BScWwLY65tKlX4CmZLGhJI8ampk2SO0mQ73jQ0XxhUguZa1IeeohsKFFs59KWztuikEGkgukPy/2y0aIeAnRatbsATO2+l7lCV3X401PB71ZsZzAJ8UDr3aggoWObcIkbImzpUeM=,iv:rWqG06QrCJBmyNYlZkdE9d49eyhVkYGpUAF605IMZ+A=,tag:6DL20O1bcv5G724pErXomA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
