rclone_config: ENC[AES256_GCM,data:2goZqxar/zvHMEgrJI2x89v5uB1G09xDiSd14xKHwxgavEGvBFCg0styanApI7Lx1/LcO061OeePZlrWkipuMyWpOWDPFmqD3V8i4q8cGyLA47e3XFIG3PKK4iglg13HPKbjf4MVQuM3BC2TL2/yM1qlxeEI19AxJRMF0ywN0OKghVSGVsYc1l8WFbSAeo/HkHnG6bZiGjdeq5JLaafUpwhCRMhj+8zLgIFB7WKRQtqjIZHnehYy4QxQblwS5Xc4jBhiR3AJJkZmnb777Xw43eygjaL7chKbsnP1b+oEB9CaUnx4dvPDagpoHQ3AT5jL06yS+JNamhVMARcV7HFJ7iwao89rPzkq29foeTreME5e/GMSAoOEM6GPstOD/u3eJUJC2OsK4qpOzdDEn8OL+uyoJ3wwZpsOtWROfBw+pDNMB05hrzMMDxM057UnWECXciEFXSuPIKLxwKhf,iv:1ae9Ad8jWhe6cjCUzMZiOjwNaCps7qxbi6hxGYK2al8=,tag:InOZSDq8kwyz5PCWdNU65A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUzVmeEVHRjhlclJPcGxx
            eWxtNWtzd2FuN284YlpmN1IzU3NWd2Y0ZnlrCnBkMFhPYWd5d2dsc1YyL0M3VVl1
            TlNWZVFITmcrVWpNb1RnYk1JbWJTb0kKLS0tIHdxNUkzc1VLR3NCL3BBdXNuT1Rv
            bHFCcmlhRGhTZDZkUG9ocVVlY2FEY2sK/CI4Q3XMNgJk+tayljIFmKmA772ARyX8
            ZVO2ZKTfDJvDrkUhUxnyJSqDtTRbRoMHW70IZhpMoh9DIyw1Pp/ZUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j0e09hj4w5u228jee09a3e8wq0x3g8nmchfmfgwvk00m8u3w8uzskynfjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKajNiQU80VHMyR29aYXRo
            YTlSbFhqWERIb3pobmRyREpIeFhKSDBUNVZvCldBTFBoYWp3bHdRbUtBMElkdGxB
            amlKQ3dWU0ozOHhoM1hvNHN0U1k3UDAKLS0tIERGQWxDQWpOZ0pOSTM2TU9nRmtt
            TGR6ZlovMTBzdC9OSWpkZVNSRncyL00K+0Ds8m0NOmXVyf4TCWoSh9OLVDN4CPDq
            cVkArqgB7qnmNOODEJl91VEdvO50mcTxtBMrplQ0m9P4YzPAHKoYSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jn6rnqfckpay0g5m5dat6z08flr6esrdjdukmpehv06ulpl6lfhq63e5n2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZnE5blBIODd3UU9yVlV4
            akpCVzhIdHRaK1djNjR1TjNHdkxRZmxQUnc0CnRESG1URFZBNGUwekJkdURVZFpD
            ckxZRWlrMHNrQTh6VG8zUS9QTmF0Z00KLS0tIEQvQUtzV2ZPT2dZYll2SW8vcnF4
            WDBTVFFxTDdnUFdtSU9hR2QrTW5jMncKaRC43LToQJyfI5cDaTF1Bjc4Rp7nbuIO
            3LRQsPZCcLWKdMCMhuy+gj1HdO3Y811gqzbLFQikr57dh/UDmway6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T03:12:04Z"
    mac: ENC[AES256_GCM,data:T04+6ixAhtzgvNJNxrBFNOv6mOAxSo29+13BScWwLY65tKlX4CmZLGhJI8ampk2SO0mQ73jQ0XxhUguZa1IeeohsKFFs59KWztuikEGkgukPy/2y0aIeAnRatbsATO2+l7lCV3X401PB71ZsZzAJ8UDr3aggoWObcIkbImzpUeM=,iv:rWqG06QrCJBmyNYlZkdE9d49eyhVkYGpUAF605IMZ+A=,tag:6DL20O1bcv5G724pErXomA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
