rclone_config: ENC[AES256_GCM,data:2goZqxar/zvHMEgrJI2x89v5uB1G09xDiSd14xKHwxgavEGvBFCg0styanApI7Lx1/LcO061OeePZlrWkipuMyWpOWDPFmqD3V8i4q8cGyLA47e3XFIG3PKK4iglg13HPKbjf4MVQuM3BC2TL2/yM1qlxeEI19AxJRMF0ywN0OKghVSGVsYc1l8WFbSAeo/HkHnG6bZiGjdeq5JLaafUpwhCRMhj+8zLgIFB7WKRQtqjIZHnehYy4QxQblwS5Xc4jBhiR3AJJkZmnb777Xw43eygjaL7chKbsnP1b+oEB9CaUnx4dvPDagpoHQ3AT5jL06yS+JNamhVMARcV7HFJ7iwao89rPzkq29foeTreME5e/GMSAoOEM6GPstOD/u3eJUJC2OsK4qpOzdDEn8OL+uyoJ3wwZpsOtWROfBw+pDNMB05hrzMMDxM057UnWECXciEFXSuPIKLxwKhf,iv:1ae9Ad8jWhe6cjCUzMZiOjwNaCps7qxbi6hxGYK2al8=,tag:InOZSDq8kwyz5PCWdNU65A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYkRwaXBab1RSaktUWGNh
            bXhacTBRa204UDdZR0JvQ0Z6SDhBcjBkQXgwCkdQVkFxSjRpendzM3pPQ25KOWw5
            WDhOZ3NaWE9uR2Flc3lyUHNMV1B2Z1UKLS0tIFFlZGo5b202Y1l6MlJJcG85ZXl1
            YXQvcHlqTVN5VnlXQ0Z4SzZLNmVhYkEKagN5Dcic5Iwva9fO4LvAgfP2hINapuF7
            oxi58diIYnHq+XA8gLuCVKIv+wb2Ai96ueDmXt3VpPOcs9puXW008w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j0e09hj4w5u228jee09a3e8wq0x3g8nmchfmfgwvk00m8u3w8uzskynfjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YVJIR1NpNVdWQlVWUVdS
            OHl5NXJnQmU1UndkRDFmTDRUR1FxaEh2VGpRCk8xVWZONUc2cVJuVFlBQ3FNMGF2
            bXdrK2xpSUpPa3dsKys5MjNnTFE1Mk0KLS0tIFB3dWRDOWZUR0Y2cGlsZ0RIVUlU
            K2hpTEgxS0l6SnFyNzRlSlZSSHdOL0UKTMj9Y9ZjT+ojqBhxdmNhyhsfe1HMJ/Rt
            lqFzlmogZl7Eixx90NvGvhqL/vDJjTl7KxPZYMkKbnMS+xNI2Tw5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T03:12:04Z"
    mac: ENC[AES256_GCM,data:T04+6ixAhtzgvNJNxrBFNOv6mOAxSo29+13BScWwLY65tKlX4CmZLGhJI8ampk2SO0mQ73jQ0XxhUguZa1IeeohsKFFs59KWztuikEGkgukPy/2y0aIeAnRatbsATO2+l7lCV3X401PB71ZsZzAJ8UDr3aggoWObcIkbImzpUeM=,iv:rWqG06QrCJBmyNYlZkdE9d49eyhVkYGpUAF605IMZ+A=,tag:6DL20O1bcv5G724pErXomA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
