[buildPlans.IosevkaTeapot]
family = "Iosevka Teapot"
spacing = "fontconfig-mono"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaTeapot.variants.design]
capital-z = "straight-serifed"
f = "flat-hook-serifed"
x = "curly-serifless"
caret = "high"
number-sign = "upright"
at = "threefold-tall"
dollar = "open"
percent = "rings-segmented-slash"

[buildPlans.IosevkaTeapot.variants.italic]
x = "curly-serifless"
z = "cursive"

[buildPlans.IosevkaTeapot.variants.oblique]
x = "curly-serifless"

[buildPlans.IosevkaTeapot.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaTeapot.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTeapot.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaTeapot.weights.Bold]
shape = 700
menu = 700
css = 700
