[buildPlans.iosevka-teapot]
family = "Iosevka Teapot"
spacing = "fontconfig-mono"
serifs = "slab"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.iosevka-teapot.variants.design]
capital-z = "straight-serifed"
f = "flat-hook-serifed"
x = "curly-serifless"
caret = "high"
number-sign = "upright"
at = "threefold-tall"
dollar = "open"
percent = "rings-segmented-slash"

[buildPlans.iosevka-teapot.variants.italic]
x = "curly-serifless"
z = "cursive"

[buildPlans.iosevka-teapot.variants.oblique]
x = "curly-serifless"

[buildPlans.iosevka-teapot.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-teapot.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-teapot.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-teapot.weights.bold]
shape = 700
menu = 700
css = 700
