dnscrypt_conf: ENC[AES256_GCM,data:6cvLsGmQ408XEynzw8zRz510n4q7p/Zhd9cngxJ+uoQ6+mAtc/rh/OTjVo76sS4/KGC/WSRJyojRkaSygeSZsyKnBO7GDG4K4Kml+jlw3n2uQ/GDNWOD0vrKUuofZT9A3ZeZoRRJUO9D2VVxmEfSwEpFrCo0FYazF5GKUCVR5iVHpxNb2JZHmvab5bP3T9//Z7D7nDKVTroXD8jr2pLAkxUer+8OfxoZwNM2Q+5IhjX9tcb73fWZmdLqdmfwuJ4B6c9Uzf3cftmvCNe37u4VlI9H9wi57D5snDWeMXuMi5rh4zQjPueKODPbK5zn1EXXmDmwsPynLZUTwYvXH5VAruAP/a1beRC0GaVRufs/Z69pFp9C3Uxa3+SHXJy9d/LltOtyGxEkEz3AsIMTL0KnbFs5WUjbCVdlcA0uMP44EyKdXloGx/rJTJ9Y+6QZq6fZXoj8t97Qu1Phd+9RiybT3dEwXLGU2Bvg1B7BtXGQSQyTg3pjajl0buDVMLBveSE8NshLIKk5S/FTqa7EwKq5XsNPga2fd+xfeEo75PVEjW6zeMCe2Hw2tpAW3TCEc2Tx8H8Iud8NqJChMGZZjrumsSkWsZmehr68hmcpRvGVuYWN8uM46/md0IVlbqunNmkL6B2ovqNOowJH21xnGEWh/0b7ehR+US4+nOIUf4DKU/Z+FWqcMJEWDHhOf4neif/EwmYK61WcBdMNKQpbEHZShwidTxIiGxpjPPpk9XCX15fqc4YDFl19OKHs4+IF1Ro/iGVx3hMytr6QjuuxkKBDRyDgTH30Siwg7yduVelvkufNZ5N6hpOHwMXdPIryhui4ZxYtg+m9UhppunSKag5wc64/1mm5wPCXqOiamthX24/kSR5fFaDtYnnm6gk8cqAHMeE+n/tCrzKUF7yRo9qWY069Wdv2/i+X78G5wMehzmxhU8Nd11b6pysvxfD2iA5WjLnm9P3eylx2pjo1vmwcnryU8iQxWagUXoAVJc5+2Rei1BEoWXgwS5uc5wa8ZZd/8FPJLJ4hpIdNP+iBjQ==,iv:bY+xfMCaKPHinLZBGPdoYbmc/gzeFTFyigs+Qh9nXHg=,tag:46IoSpFdaYk3rlWuN0AhWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUUVUYUIzY3AvU0phU3Nx
            TU5xY2JFblovZW9RL05PaVZ1S0dQdEFGbmo0Ck5YYjRoTEgrZVNScCtRL1FNTFAz
            U2VWUDRZYy8zWlZmMmVER3lGamxPVjAKLS0tIFhRZDVIdStpVTZqMXlNd3dzdlY3
            YWx5NXJXYzNZYm1EVThyeTlyYkRObkUKMT2wRm22BC0zwC7YILCD/Q9y6aBt/XHA
            b07FqggrceHVqWqtKYdsQD02EEUFH18iHfLm7WmXvDAKhT6uV35Ntg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n7wt2ctw9ep8cll7lfrh4j69wr608ayxru3cpztljj0v3vm6qyms47fys4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadG82TE5pamdaQ0grQjdF
            dDRkMXpIMUlBbVhFTlNwaGc0TENuOU1ZZ3pRCklvL2tBckRNWkp1NnA0eXVURGZ2
            SGdvZU1nV3RHcWhvSTNzeGN6WlAxNncKLS0tIHpiczU4blpEbkRydHZJTnpIZm9C
            NC9wU2RjSUpCckZlNWcyNytVRDduYVUKq1VbSoteIkDFuIYHzzH8OpZVi0fSVSZP
            54CXmmVJsIWYCAyYjg1Vfu8g2oVu6Y2RcjiBdjlleIJDAhC+peLjKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-04T11:01:14Z"
    mac: ENC[AES256_GCM,data:Za8Ym3W8dQpWZE6iEvZ+mzDwkdR1AI+9RBaG6IA6eIcQxPY1sk4hdgvyPD8XAucXuvvetj79AE9p1pVPSL4Fj4HKd+mv2//LnRjR1aX5C8NcIJ9U+r82R6DLbyEHp/eenqP2D/zWCGvphfZP1+huJAffZO0LH3CEdkkRutf45mI=,iv:Qk1EYSR4Z2lpu497lCi97H9dC9VrA9B3cTWs4vRui/M=,tag:ipCU0K0n6lS24VKgadbowA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
