dnscrypt_conf: ENC[AES256_GCM,data:flC3Dd2rzkjTbLYTXyBXIjckRNUI2bDt+IX4oE+uzdaby0OdGf0irZ+m77Ls3Rg0N+z48YhbbBvVx64lFYooDc1ovtjpFuelDlZOAaNe0mtugeSS/BBp8oVlz4PHMUwPhxbnLvXyk15n8RurU/83NTH4/sfwS/oClzKTfHsLzjttwLvaqqMPMsbXBgkbSs+izDWwz3quBKa8Wlczw/aVXCVZ/tVOwVXV97LVeErz/mQFLkhxAGzBNwfm08wT6+L4jWipNHU02abfiuW12IQIhs2/IksnVyTlj/Xh2+1BfI/1O+Ap/YJLm6tdq+GbJFDPZWQZt7oxovXkR2dhEEmlsK75QK4hyWZOh+eLR+PwLzD5m4Ebrpc8MSHWkWTR+o6aLf6NR3CeXKhoGDCAcuEoZndvYB9JD020Gpph1pRnFAY93yiA6+v3iikLckqcchpWDrwboknMIa/Fp916KB9LqpRKjTyrbMr3o6NFIdV5vmq6NFbA5P6UUJdVnZ4g3YDJUNcgiiG46+E+dvIbgPRD0SPe39/VKNIfFYRVkSWdJFsl0KU369gyji2g6x54amz+zPQblINImuH6w35vfxo9c9+ICtx2Vo6kk0Kt3OGuBN9yHBfj/+ELr3q7S0HquCSD6PPF+80XsnvuYtP2yM+20pKLdUTtGBC4+tNzyr5Q5bUXr0aBoNfxTM4zV3lhHoFWZxLysVj5FwGkYS5hJ9aCTwxoeeI4tEjFQkM77h+LDUfEaJNT3PnnEFA1JI7291W2fRFF2fRaMLaaLlXlw0B7AtTs0E4AyfmyHK7MNIfY27peSFdmFBE8oyIUYw2/mIRGPoNNOnJ7E8JOQfM6RLBZN8c7C3Jb7oLRanIXKZ+Mtc7MINOwUxkSVTM2Nuog+tQoyF/bo/RK/U+Mo3CHDodWE74YcybuwleAJcWr6ffSQ3BKd266Q0FQEhFK03MlEtqVxQwOYCutdu5wcrEl7rVPNeKnPtBatGLE5RKdgl5SHcS9pV2soFvBkplS4YjoOllRaLK8isZjKndqLOITu//qJCTKNAusRnFjwqBfZchwq+nQ+K8=,iv:C4B9eA5gjYTm3FizbMCE0xpRM+VaP9IW0c+jKFY/Um0=,tag:LEY/V1QPcvea6TQDOa8VpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUUVUYUIzY3AvU0phU3Nx
            TU5xY2JFblovZW9RL05PaVZ1S0dQdEFGbmo0Ck5YYjRoTEgrZVNScCtRL1FNTFAz
            U2VWUDRZYy8zWlZmMmVER3lGamxPVjAKLS0tIFhRZDVIdStpVTZqMXlNd3dzdlY3
            YWx5NXJXYzNZYm1EVThyeTlyYkRObkUKMT2wRm22BC0zwC7YILCD/Q9y6aBt/XHA
            b07FqggrceHVqWqtKYdsQD02EEUFH18iHfLm7WmXvDAKhT6uV35Ntg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n7wt2ctw9ep8cll7lfrh4j69wr608ayxru3cpztljj0v3vm6qyms47fys4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadG82TE5pamdaQ0grQjdF
            dDRkMXpIMUlBbVhFTlNwaGc0TENuOU1ZZ3pRCklvL2tBckRNWkp1NnA0eXVURGZ2
            SGdvZU1nV3RHcWhvSTNzeGN6WlAxNncKLS0tIHpiczU4blpEbkRydHZJTnpIZm9C
            NC9wU2RjSUpCckZlNWcyNytVRDduYVUKq1VbSoteIkDFuIYHzzH8OpZVi0fSVSZP
            54CXmmVJsIWYCAyYjg1Vfu8g2oVu6Y2RcjiBdjlleIJDAhC+peLjKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-13T02:07:02Z"
    mac: ENC[AES256_GCM,data:FS+ezFKMExo0xBR3GthDIqtmww7crZ3sElR607nu6Bl9rMUjcv7DiVIXeP8sccm+DfPjE7euqfm43HwdLKDt/Zk+IxjMGLo87UCRN8bU0wslvVFwauAl4IZpJaxWBz4NdI+ExkS+DB0mMKHqN+/vacaGADd4SUCBcrPPfpvwZKQ=,iv:bZ6vp9CmX2Gh22XEVg2xivSXcKkBuQ8DYRa1jzBlKdg=,tag:jVHLfdiGKQefZVJInI9ycQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
