dnscrypt_conf: ENC[AES256_GCM,data:WXj2BzyxryuS8NFSWNzwtpLTzWJrEdXukpz780vIvtCugz/kX+MTAmmRFZKA9Nr3rIiZHhhIbvy0rbNehpX0ZRqel1vPEy6NQ4XMZjVDm444aatHTrjz53O+JkUZ1ZTlGsb543YoK1anJ4VrUqnGwE8XqOXAICh7CH4MU5B5S+8KyIBEdmE+C9Kc9qzuxk6AxXJHyAu0FvZmcrdFLJz4VJcogHF+W93NzGNjIqFPnCszQuCsNC8QKdSl2aUkLf5z8HMoBqoyvMFOt1lVGtPxFkU31i/Mi8JyLVwc7m2UY6dwROmhKETdOY3FKsvnx5vAa6X2Y1+9b+JWc+qDo3xt27nXTp9n9aN1tWHOma7FO+woP8CNmR89iuCYp2GQuvF7Y8JydvAVX7/Shu4fcB5X8oYyl0mFn/Y7QxaO5JPO/18GDf0P8MM7XE6PRbD95ZUa8xGDOb1ju+JPbxsk1a0ZJ1gp3uaUv46pTudyEzoIWiXlKnGfai2ZMe/6LZ1kSAV/LX6J6SoZKI8Dl3FcL726nCR7eXlTzTxmFQUcQNhghmRHBXmwV28tsdiRtRi3U+z9dgWYH6faWX8Jge+bFKdU/Sly1jL4f1nMYHn1KtTxKCRN6sq4UzGUBjk1uxOM8KKSF8qn6J+5+usQlxTt8zRju8H/CGGvEE9grGFmKc99w0aMQg3gPjZFRmlmL4pH/CAS/df/eQbXI7jVOMDVhP+N6UDh1W9AX36Pl12DQ6cHMoS3G/599ebU75jc/m7JycsylFkgwv12NohP3iy+0X6qCC6uVIzIm5qE24SwXxWZXbROkG6cyQjxT3HB70BKtRqDwB2sxq/aD3bHVPkOfM5BuIu2eHw5mv5XcDLijzmZHggQNdnwJ7+QQfuisb3+Wq3UHQSy4fo8nnAuovXuFDcSQr7nnQSQEUxKABVxRIGdAx/7zoufAlaTn04f1XsXK0XkNzUwwmVHaFUUDOv829qURM8loWNc7y/z3tMYBQEFxw7A8Pecne6PBNkSNLAwkkdfsH0F6qha9lwvTVkdZv0mwAZfjBrEL0gaM4mN5yrkjDzykizE5xWUlwiVyRDgvrHNCTgz+YFkCPlCQ0tOYtjS2nCk1g==,iv:lyqbIfVILHe8NxRagxbTl7WOfFyN4sUb3K+7v8fVrGI=,tag:dAJq143bEdZWqgWEV3oMBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUUVUYUIzY3AvU0phU3Nx
            TU5xY2JFblovZW9RL05PaVZ1S0dQdEFGbmo0Ck5YYjRoTEgrZVNScCtRL1FNTFAz
            U2VWUDRZYy8zWlZmMmVER3lGamxPVjAKLS0tIFhRZDVIdStpVTZqMXlNd3dzdlY3
            YWx5NXJXYzNZYm1EVThyeTlyYkRObkUKMT2wRm22BC0zwC7YILCD/Q9y6aBt/XHA
            b07FqggrceHVqWqtKYdsQD02EEUFH18iHfLm7WmXvDAKhT6uV35Ntg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n7wt2ctw9ep8cll7lfrh4j69wr608ayxru3cpztljj0v3vm6qyms47fys4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadG82TE5pamdaQ0grQjdF
            dDRkMXpIMUlBbVhFTlNwaGc0TENuOU1ZZ3pRCklvL2tBckRNWkp1NnA0eXVURGZ2
            SGdvZU1nV3RHcWhvSTNzeGN6WlAxNncKLS0tIHpiczU4blpEbkRydHZJTnpIZm9C
            NC9wU2RjSUpCckZlNWcyNytVRDduYVUKq1VbSoteIkDFuIYHzzH8OpZVi0fSVSZP
            54CXmmVJsIWYCAyYjg1Vfu8g2oVu6Y2RcjiBdjlleIJDAhC+peLjKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T00:58:16Z"
    mac: ENC[AES256_GCM,data:gYSF/djpi/Zam8URj7eOXTHSfY7qubIKnbNKggyYrW2cX/NxE4/HbV3CYR7IEjfnFVbjemU8CIyA6SyZx4JybNyqZSR7mStnlcC/7flUvXVgp1f/Zl1lJ5gyBqowxtX4CgI2kzh3h5Wz2/KzebfTSHaXJYz7sU9mCDKkxwrA/wk=,iv:Og53/kL6DhhKuq+huWayIkzO43Ic9fvF6QDfnxrZeMs=,tag:Lh+0OFJDaczhH0CBIi+SBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
