dnscrypt_config: ENC[AES256_GCM,data:UzaReeLbzWKAmapyG4ObPxom15KPZTe/XZHRpkGnLcUIDsk7iXRLAxskfWJNvHpVKNnyGivA6K6T4VhXCZDPeg7JUaaC7xOq3Pbk4zFHUbGhDzeNJrWuAfDN2LYrN7U0REkKN0W/uMk0Zdj/9G599TPIe5QJxoEV7IWqh36tIc1isdlOJ0SpyrA649i+eO6biQoNcPtmlBWOgVg/wsgbQCKvf5cfnuBmePoTpd/19mY6PyPRasJ3SFWAKelvCk6L1yCPfg+422EupadP7nI+igHuFFiZoZpQz2L9MntonM5esdbQ+CQFNy6426dR0JAZ/WQcadtBP9c5o0V/NLSt5mCb6iXWnFfUvASiAvtUxdU39tN++RM0QKwpXE9aPsX9wqoS07gBVsYK9Ci5hDJm9xgAW3qX0ULCW6d49oX4L6h/Q2md59KUt/yZ30oKQ3+iyxHSJ1WvzuCmadpX+2JS+GOxq56ibTeO88cqh8D2yx1pMQKEJ+5Cij565L2JETEIxz/m2y5t2UhWcBCXZHUYOuiGCxcR0vlgiQscx8y9FqWNnrTGUJGhfwYQjRduCui5/emNBWvrbmPti+SLF6zrrCirDMuj+bWH2uDQZTFb4SiUpRBUMMKkISnpH8V3M2qDSUdkLqFDHFWOCYvKWNldRv+2MjFkimucrGzeWX9I6fIZAwW9SKlzSk5TZKEfYcDAy3uzWosrXlco4Lfma/HsYrqwM9AT1JClmZ8PnhL8Yufz6BjO6pLfaGAmKp/5+aBefn/lK0nJ4hA9ZBau2WmKO9zMWrvIytD8BUQxcwpIXl9D7/MOMDlqgae5sggHFHF3Q6yfv8g7qwsoMV/frgRTby0yGPBURFM3g84xk9fk6FvGJM3vFTXGjQKTKIlB2qw1yaxb3z/mcer5ytqqX505bbNtmk+okB5w9HEF0hlsr9wwWUzXLM9YxzScS1JIyu+Dx6IGHWDIXPG/BfkF+rYi0P6Z28OSOdSXST/negW878MjwpmpphSj33SOA4nfI3cZq1X4oGR4h0uE8Kvd8lWlropVjv3KcsRQGpsRdx2xCTyijZl1Rn1dW9wTG4IWtg2Zf3/QEDh7d78JdkHeOG8BSgdJ62JTjwi4wQWYjZQqWgj/sPwT458xabsZX42UYZdjaWYgJ58Ez5Bbw35NaIV6hKZmziWy8X86xbaQ4W/DBk7lUZ41nNpfwNqS3M7hgNObi6LESEu8egydQjOGg4xzwZK324sVfAsopfCGFdRDVYweRUSuHzNUN5CF6HD2jw3LTy/he7vMh9o9sTnb4wYdn6APWmI+9uQ46EO8zPP+vxqizFblu0hoqHNygK5IA+PMJa1jfc6kloYpiVrU1sJm7sumaQfDh4ao0BMU,iv:js6he2ACPRf9coJfACxKk1rSNIr5yYdDF3byXk/vUhc=,tag:2RmWTxr9jRP0sMSEbec0WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17lvnmh99feams2pvfljw34k5s705uk89x6g26r4ml85yu0h2q9uswpmjm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUUVUYUIzY3AvU0phU3Nx
            TU5xY2JFblovZW9RL05PaVZ1S0dQdEFGbmo0Ck5YYjRoTEgrZVNScCtRL1FNTFAz
            U2VWUDRZYy8zWlZmMmVER3lGamxPVjAKLS0tIFhRZDVIdStpVTZqMXlNd3dzdlY3
            YWx5NXJXYzNZYm1EVThyeTlyYkRObkUKMT2wRm22BC0zwC7YILCD/Q9y6aBt/XHA
            b07FqggrceHVqWqtKYdsQD02EEUFH18iHfLm7WmXvDAKhT6uV35Ntg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n7wt2ctw9ep8cll7lfrh4j69wr608ayxru3cpztljj0v3vm6qyms47fys4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadG82TE5pamdaQ0grQjdF
            dDRkMXpIMUlBbVhFTlNwaGc0TENuOU1ZZ3pRCklvL2tBckRNWkp1NnA0eXVURGZ2
            SGdvZU1nV3RHcWhvSTNzeGN6WlAxNncKLS0tIHpiczU4blpEbkRydHZJTnpIZm9C
            NC9wU2RjSUpCckZlNWcyNytVRDduYVUKq1VbSoteIkDFuIYHzzH8OpZVi0fSVSZP
            54CXmmVJsIWYCAyYjg1Vfu8g2oVu6Y2RcjiBdjlleIJDAhC+peLjKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-30T00:43:52Z"
    mac: ENC[AES256_GCM,data:vV9V9UPVIl4a7T0BXI17AoNk1yLMGc7HI1LnI04Aipqw9zblGAIzb/PJoMunAAQDTpME2hPn2JHNBkfvdwLnfmViHY/xHKSV8ZFKh5ViOfTybc1guqZDyBTWfgLY/2UlEo1Wnero73retdQOfiQa6yvCIa6WH0MpRQ/keAOEgrw=,iv:rTXFU/Ilp/Ar10gPC3Iw/U/MlpiCdnMKIpOH9nVFygo=,tag:5q4VCCwDDG/A/hQGAZ135Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
