//! Runtime configuration.
//!
//! A JSON config file generated by the NixOS module -- explicit
//! types, upfront validation, no shell-style `psd.conf`.

use std::env;
use std::fs::read_to_string;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Context as _;
use anyhow::Result;
use serde::Deserialize;

use crate::apps::AppKind;

#[derive(Debug, Deserialize)]
pub struct Config {
    /// Apps to manage. Must be non-empty.
    pub apps: Vec<AppKind>,
}

impl Config {
    /// Load from a JSON file.
    pub fn load(path: &Path) -> Result<Self> {
        let raw = read_to_string(path).with_context(|| {
            format!("reading config {}", path.display())
        })?;
        let mut cfg: Self =
            serde_json::from_str(&raw).with_context(|| {
                format!("parsing config {}", path.display())
            })?;
        if cfg.apps.is_empty() {
            anyhow::bail!("config: `apps` must not be empty");
        }
        // Dedupe: duplicate entries would manage each profile twice.
        cfg.apps.sort_unstable_by(|a, b| a.as_ref().cmp(b.as_ref()));
        cfg.apps.dedup();
        Ok(cfg)
    }

    /// Default config path: `$XDG_CONFIG_HOME/psd/config.json` (only
    /// when absolute, per the XDG spec), falling back to
    /// `~/.config/psd/config.json`.
    pub fn default_path() -> Result<PathBuf> {
        if let Ok(config_home) = env::var("XDG_CONFIG_HOME")
            && Path::new(&config_home).is_absolute()
        {
            return Ok(PathBuf::from(config_home).join("psd/config.json"));
        }
        let home = env::home_dir()
            .context("could not determine home directory")?;
        Ok(home.join(".config/psd/config.json"))
    }
}
