use std::collections::HashMap;
use std::fs::create_dir_all;
use std::path::PathBuf;
use std::sync::LazyLock;

use anyhow::Context as _;
use anyhow::Result as AnyResult;
use anyhow::ensure;

static SYSTEMD_NETWORK_DIR: LazyLock<PathBuf> =
    LazyLock::new(|| PathBuf::from("/run/systemd/network"));

const PREFIX: &str = "00-mimic-cloud-init";

#[derive(Debug)]
#[derive(serde::Deserialize)]
struct NetworkConfig {
    version: usize,
    ethernets: HashMap<String, Ether>,
}

#[derive(Debug)]
#[derive(serde::Deserialize)]
struct Ether {
    r#match: EtherMatch,
    addresses: Option<Vec<String>>,
    gateway4: Option<String>,
    gateway6: Option<String>,
    nameservers: Option<Nameserver>,
}

#[derive(Debug)]
#[derive(serde::Deserialize)]
struct EtherMatch {
    name: Option<String>,
    macaddress: Option<String>,
}

#[derive(Debug)]
#[derive(serde::Deserialize)]
struct Nameserver {
    addresses: Vec<String>,
}

pub fn render_network_config(conf_str: &str) -> AnyResult<()> {
    eprintln!("rendering network config");

    let config: NetworkConfig = serde_yaml_ng::from_str(conf_str)
        .context("Failed to parse network config yaml")?;
    ensure!(config.version == 2, "This tool only supports v2");
    &config;

    let mut networkd_configs: Vec<(String, String)> = vec![];

    for (iface, ether) in config.ethernets {
        let mut lines: Vec<String> = vec![];

        lines.push("# Generated by mimic-cloud-init".into());

        // [Match]
        lines.push("[Match]".into());
        // TODO: name is tricky to handle
        if let Some(name) = ether.r#match.name {
            lines.push("# Name match is left unused".into());
            lines.push(format!("# Name = {name}"));
        }
        if let Some(mac) = ether.r#match.macaddress {
            lines.push(format!("MACAddress = {mac}"));
        }
        lines.push("\n".into());

        // [Address]
        if let Some(addrs) = ether.addresses {
            for a in addrs {
                lines.push("[Address]".into());
                lines.push(format!("Address = {a}"));
            }
        }
        lines.push("\n".into());

        // [Route]
        if let Some(g4) = ether.gateway4 {
            lines.push("[Route]".into());
            lines.push(format!("Gateway = {g4}"));
        }
        if let Some(g6) = ether.gateway6 {
            lines.push("[Route]".into());
            lines.push(format!("Gateway = {g6}"));
            lines.push("GatewayOnLink = yes".into());
        }
        lines.push("\n".into());

        // [Network]
        lines.push("[Network]".into());
        lines.push("DHCP = no".into());
        // N.B. DNS is commented out.
        if let Some(ns) = ether.nameservers {
            lines.push("# DNS from cloud-init is not used".into());
            lines.push(format!("# DNS = {}", ns.addresses.join(" ")));
        }
        lines.push("\n".into());

        let conf_name = format!("{PREFIX}-{iface}.network");
        networkd_configs.push((conf_name, lines.join("\n")));
    }

    if !networkd_configs.is_empty() {
        eprintln!("write netword config");
        create_dir_all(&*SYSTEMD_NETWORK_DIR)?;

        for (name, content) in networkd_configs {
            let full_path = &SYSTEMD_NETWORK_DIR.join(name);
            &full_path;
            std::fs::write(full_path, content).with_context(|| {
                format!(
                    "Failed to write networkd config {}",
                    full_path.display()
                )
            })?;
        }
    }

    Ok(())
}
