#!/usr/bin/env -S sh -c 'exec `dirname $0`/__script/nvfetcher "$0" "$@"'

# Network

[shadowsocks-rust]
src.github = "shadowsocks/shadowsocks-rust"
fetch.github = "shadowsocks/shadowsocks-rust"
extract = [ "Cargo.lock" ]

[dnsproxy]
src.github = "AdguardTeam/dnsproxy"
fetch.url = "https://github.com/AdguardTeam/dnsproxy/releases/download/$ver/dnsproxy-linux-amd64-$ver.tar.gz"

[hysteria]
src.github = "apernet/hysteria"
fetch.url = "https://github.com/apernet/hysteria/releases/download/$ver/hysteria-linux-amd64-avx"

# Editor

[neovim]
src.git = "https://github.com/neovim/neovim"
fetch.git = "https://github.com/neovim/neovim"

# Language

# Utility

[derputils]
src.git = "https://github.com/MidAutumnMoon/derputils"
fetch.git = "https://github.com/MidAutumnMoon/derputils"
extract = [ "Cargo.lock" ]

[k380-fn-keys-swap]
src.git = "https://github.com/jergusg/k380-function-keys-conf/"
fetch.git = "https://github.com/jergusg/k380-function-keys-conf/"

# Shterm

[tide]
src.github = "IlanCosman/tide"
fetch.github = "IlanCosman/tide"

[puffer-fish]
src.git = "https://github.com/nickeb96/puffer-fish"
fetch.git = "https://github.com/nickeb96/puffer-fish"

# Entertain

# Kernel

[cachyos-patches]
src.git = "https://github.com/CachyOS/kernel-patches/"
fetch.git = "https://github.com/CachyOS/kernel-patches/"
#pinned = true

# Color & Themes & Font

[graphite-cursors]
src.github = "vinceliuice/Graphite-cursors"
fetch.github = "vinceliuice/Graphite-cursors"

[zhudou-sans]
src.github = "Buernia/Zhudou-Sans"
fetch.github = "Buernia/Zhudou-Sans"

[ibm-plex]
src.github = "IBM/plex"
fetch.url = "https://github.com/IBM/plex/releases/download/$ver/OpenType.zip"

# Warehouse
