#!/usr/bin/env -S sh -c 'exec `dirname $0`/__script/nvfetcher "$0" "$@"'

# Network

[shadowsocks-rust]
src.github = "shadowsocks/shadowsocks-rust"
fetch.github = "shadowsocks/shadowsocks-rust"
extract = [ "Cargo.lock" ]

# Editor

[neovim]
src.git = "https://github.com/neovim/neovim"
fetch.git = "https://github.com/neovim/neovim"

# Language

[moonscript]
src.git = "https://github.com/leafo/moonscript"
fetch.git = "https://github.com/leafo/moonscript"

# Utility

[derputils]
src.git = "https://github.com/MidAutumnMoon/derputils"
fetch.git = "https://github.com/MidAutumnMoon/derputils"
extract = [ "Cargo.lock" ]

[k380-fn-keys-swap]
src.git = "https://github.com/jergusg/k380-function-keys-conf/"
fetch.git = "https://github.com/jergusg/k380-function-keys-conf/"

[watchgha]
src.git = "https://github.com/nedbat/watchgha"
fetch.git = "https://github.com/nedbat/watchgha"

# Shterm

[tide]
src.github = "IlanCosman/tide"
fetch.github = "IlanCosman/tide"

[puffer-fish]
src.git = "https://github.com/nickeb96/puffer-fish"
fetch.git = "https://github.com/nickeb96/puffer-fish"

# Entertain

# Kernel

[cachyos-patches]
src.git = "https://github.com/CachyOS/kernel-patches/"
fetch.git = "https://github.com/CachyOS/kernel-patches/"
pinned = true

# Color & Themes & Font

[graphite-cursors]
src.github = "vinceliuice/Graphite-cursors"
fetch.github = "vinceliuice/Graphite-cursors"

[zhudou-sans]
src.github = "Buernia/Zhudou-Sans"
fetch.github = "Buernia/Zhudou-Sans"

[ibm-plex]
src.github = "IBM/plex"
fetch.url = "https://github.com/IBM/plex/releases/download/$ver/OpenType.zip"

# Warehouse

[mdbook-toc]
src.git = "https://github.com/badboy/mdbook-toc"
fetch.git = "https://github.com/badboy/mdbook-toc"
extract = [ "Cargo.lock" ]
