#!/usr/bin/env -S sh -c 'exec `dirname $0`/__script/nvfetcher "$0" "$@"'

# Network

[shadowsocks-rust]
src.git = "https://github.com/shadowsocks/shadowsocks-rust"
fetch.git = "https://github.com/shadowsocks/shadowsocks-rust"
extract = [ "Cargo.lock" ]

# Editor

[neovim]
src.git = "https://github.com/neovim/neovim"
fetch.git = "https://github.com/neovim/neovim"

# Language

[moonscript]
src.git = "https://github.com/leafo/moonscript"
fetch.git = "https://github.com/leafo/moonscript"

# Utility

[derputils]
src.git = "https://github.com/MidAutumnMoon/derputils"
fetch.git = "https://github.com/MidAutumnMoon/derputils"
extract = [ "Cargo.lock" ]

[k380-fn-keys-swap]
src.git = "https://github.com/jergusg/k380-function-keys-conf/"
fetch.git = "https://github.com/jergusg/k380-function-keys-conf/"

[watchgha]
src.git = "https://github.com/nedbat/watchgha"
fetch.git = "https://github.com/nedbat/watchgha"

# Shterm

[tide]
src.github = "IlanCosman/tide"
fetch.github = "IlanCosman/tide"

[puffer-fish]
src.git = "https://github.com/nickeb96/puffer-fish"
fetch.git = "https://github.com/nickeb96/puffer-fish"

# Entertain

[yuzu-ea-appimage]
src.github = "pineappleEA/pineapple-src"
fetch.url = "https://github.com/pineappleEA/pineapple-src/releases/download/$ver/Linux-Yuzu-$ver.AppImage"

# Kernel

[cachyos-patches]
src.git = "https://github.com/CachyOS/kernel-patches/"
fetch.git = "https://github.com/CachyOS/kernel-patches/"
pinned = true

# Color & Themes & Font

[graphite-cursors]
src.github = "vinceliuice/Graphite-cursors"
fetch.github = "vinceliuice/Graphite-cursors"

[noto-fonts-cjk]
src.github_tag = "googlefonts/noto-cjk"
src.include_regex = "Sans.*"
fetch.url = "https://github.com/googlefonts/noto-cjk/releases/download/$ver/03_NotoSansCJK-OTC.zip"

# Warehouse

[mdbook-catppuccin]
src.git = "https://github.com/catppuccin/mdBook"
fetch.git = "https://github.com/catppuccin/mdBook"
extract = [ "Cargo.lock" ]

[mdbook-toc]
src.git = "https://github.com/badboy/mdbook-toc"
fetch.git = "https://github.com/badboy/mdbook-toc"
extract = [ "Cargo.lock" ]
