# Network

[shadowsocks-rust]
src.github = "shadowsocks/shadowsocks-rust"
fetch.github = "shadowsocks/shadowsocks-rust"
extract = [ "Cargo.lock" ]

[dnsproxy]
# src.github = "AdguardTeam/dnsproxy"
# TODO: resume when Go 1.21.7 gets out of staging
src.cmd = "echo v0.64.1"
fetch.github = "AdguardTeam/dnsproxy"

# Utility

[TeapotInOri]
src.git = "https://github.com/MidAutumnMoon/TeapotInOri"
fetch.git = "https://github.com/MidAutumnMoon/TeapotInOri"
extract = [ "Cargo.lock" ]

[k380-fn-keys-swap]
src.git = "https://github.com/jergusg/k380-function-keys-conf/"
fetch.git = "https://github.com/jergusg/k380-function-keys-conf/"

# Shterm

[tide]
src.github = "IlanCosman/tide"
fetch.github = "IlanCosman/tide"

[puffer-fish]
src.git = "https://github.com/nickeb96/puffer-fish"
fetch.git = "https://github.com/nickeb96/puffer-fish"

# Color & Themes & Font

[graphite-cursors]
src.github = "vinceliuice/Graphite-cursors"
fetch.github = "vinceliuice/Graphite-cursors"

[zhudou-sans]
src.github = "Buernia/Zhudou-Sans"
fetch.github = "Buernia/Zhudou-Sans"

[ibm-plex]
src.github = "IBM/plex"
fetch.url = "https://github.com/IBM/plex/releases/download/$ver/OpenType.zip"
