# Network

[shadowsocks-rust]
src.github = "shadowsocks/shadowsocks-rust"
fetch.github = "shadowsocks/shadowsocks-rust"
extract = [ "Cargo.lock" ]

[dnsproxy]
src.github = "AdguardTeam/dnsproxy"
fetch.url = "https://github.com/AdguardTeam/dnsproxy/releases/download/$ver/dnsproxy-linux-amd64-$ver.tar.gz"

[hysteria]
src.github = "apernet/hysteria"
fetch.url = "https://github.com/apernet/hysteria/releases/download/$ver/hysteria-linux-amd64"

# Utility

[TeapotInOri]
src.git = "https://github.com/MidAutumnMoon/TeapotInOri"
fetch.git = "https://github.com/MidAutumnMoon/TeapotInOri"
extract = [ "Cargo.lock" ]

[k380-fn-keys-swap]
src.git = "https://github.com/jergusg/k380-function-keys-conf/"
fetch.git = "https://github.com/jergusg/k380-function-keys-conf/"

# Shterm

[tide]
src.github = "IlanCosman/tide"
fetch.github = "IlanCosman/tide"

[puffer-fish]
src.git = "https://github.com/nickeb96/puffer-fish"
fetch.git = "https://github.com/nickeb96/puffer-fish"

# Color & Themes & Font

[graphite-cursors]
src.github = "vinceliuice/Graphite-cursors"
fetch.github = "vinceliuice/Graphite-cursors"

[zhudou-sans]
src.github = "Buernia/Zhudou-Sans"
fetch.github = "Buernia/Zhudou-Sans"

[ibm-plex]
src.github = "IBM/plex"
fetch.url = "https://github.com/IBM/plex/releases/download/$ver/OpenType.zip"
