[book]
authors = [ "MidAutumnMoon" ]
language = "en"
src = "bubbles"
title = "Cider Bubble"

[build]
build-dir = "out"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "frappe"
mathjax-support = true
additional-css = [
    "./theme/self.css",
]

[output.html.print]
enable = false

[preprocessor.toc]
renderer = [ "html" ]
