name: "Teapot's binary cache"


on:
    workflow_dispatch:
    push:
        paths:
        - 'flake.*'
        - 'packages/**'
    schedule:
        #- cron: "0 */4 * * *"
        - cron: "0 0 */2 * *"


jobs:

    build-n-cache:

        name: "Build & Cache"

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                subject:
                - kernels-modules
                - parallel-1
                - parallel-2
                - parallel-3
                - rust-things
                - go-things


        defaults:
            run: { shell: bash }

        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup nix
          uses: MidAutumnMoon/spheti-action/nix@master

        - name: Setup cachix
          uses: cachix/cachix-action@v14
          with:
            installCommand: "nix profile install nixpkgs#cachix"
            name: "nuirrce"
            authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            cachixArgs: -c 16 -j 3 --omit-deriver
            pushFilter: |
                (NVIDIA.*\.run)|(npm-deps|-source|vendor\..*|\.tar.*$)

        - name: Update workspace flake
          run: |
            nix flake update

        - name: Run build
          run: |
              nix run --print-build-logs \
                .#nuranScripts.binary-cache-builder -- \
                "packages/manifest.nix" "${{ matrix.subject }}"
