name: "Teapot's binary cache"


on:
    workflow_dispatch:
    push:
        paths:
        - 'flake.*'
        - 'packages/**'
    schedule:
        #- cron: "0 */4 * * *"
        - cron: "0 0 */2 * *"


jobs:

    build-n-cache:

        name: "Build & Cache"

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                task-name:
                - kernels-modules
                - parallel-1
                - parallel-2
                - parallel-3
                - rust-things
                - rust-heavy-things
                - go-things


        defaults:
            run: { shell: bash }

        env:
            CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup nix
          uses: MidAutumnMoon/spheti-action/nix@master

        - name: Setup cachix
          uses: cachix/cachix-action@master
          with:
            installCommand: "nix profile install nixpkgs/nixos-23.11#cachix"
            name: "nuirrce"
            authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            cachixArgs: -c 16 -j 2 --omit-deriver
            pushFilter: |
                (NVIDIA.*\.run)|(npm-deps|-source|vendor\..*|go-modules|-crate-|\.tar.*$)

        - name: Update workspace flake
          run: |
            nix flake update

        - name: Run build
          run: |
            pushd "packages"
            fish "__scripts/builder.fish" \
                "workflow-builds.nix" \
                "${{ matrix.task-name }}"
            popd
