name: "Teapot's binary cache"

on:
  workflow_dispatch:
  push:
    paths:
      - 'flake.*'
      - 'packages/**'
  schedule:
    - cron: "0 */4 * * *"


jobs:

  build-cache:

    strategy:
      fail-fast: false
      matrix:
        task-name:
          - kernels-modules
          - parallel-1
          - parallel-2
          - parallel-3
          - rust-things
          - rust-heavy-things
          - go-things

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup nix"
        uses: cachix/install-nix-action@v22
        with:
          nix_path: "nixpkgs=channel:nixpkgs-unstable"

      - name: "Setup cachix"
        uses: cachix/cachix-action@master
        with:
          name: "nuirrce"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          cachixArgs: -c 16 -j 2 --omit-deriver
          pushFilter: |
            (NVIDIA.*\.run)|(-source|vendor\..*|go-modules|-crate-|\.tar.*$)

      - name: "Install tools"
        run: |
          nix-env -f '<nixpkgs>' -iA 'nix-build-uncached' 'fish'

      # - name: "Freeup bloats"
      #   run: fish __scripts/cleansing.fish light

      - name: "Configure nix daemon"
        run: fish __scripts/configure-daemon.fish

      - name: "Update workspace flake"
        run: nix flake update

      - name: "Run build"
        run: |
          fish __scripts/do-build.fish \
            'packages/workflow-builds.nix' \
            '${{ matrix.task-name }}'

      # - name: "Cleanup"
      #   if: always()
      #   run: nix-collect-garbage -d
