name: "Update sources"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 6 * * 1"

jobs:
    update-sources:
        runs-on: ubuntu-latest

        defaults:
            run: { shell: bash }

        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup nix
          uses: MidAutumnMoon/spheti-action/nix@master
          with:
            cachix-url: "https://nuirrce.cachix.org/"
            cachix-pubkey: "nuirrce.cachix.org-1:KQWa6ZfDkMPXeDiUpmyDhNw4CmgybPyeVklmi/1Rtqk="


        - name: Run nvfetcher
          id: nvfetcher_results
          run: |
            pushd "packages"
            declare -r TEMP="$(mktemp)"

            nix run --print-build-logs \
                .#nuranScripts.nvfetcher-driver -- "sources.toml" "__sources" "${{ github.token }}" \
            | tee "$TEMP"

            # just pivot away you f* bash
            {
                echo "content<<WHEREDOC"
                # only needs the changes in the PR
                sed '0,/^Changes/d' "$TEMP"
                echo "WHEREDOC"
            } >> "$GITHUB_OUTPUT"

            popd


        - name: Update vendorHashes
          id: update_vendorhashes
          env:
              GV_DEBUG: "1"
          run: |
              pushd "packages"

              declare -r Manifest=$( nix eval .#vendorhash.manifest --json | jq -r '.[]' )

              echo "content<<WHEREDOC" >> "$GITHUB_OUTPUT"

              for pkg in $Manifest; do
                attr=".#${pkg}"
                outfile="__vendorhash/${pkg}"
                mkdir -p $(dirname $outfile)
                diff="$( nix run --print-build-logs \
                    .#nuranScripts.goaway-vendorhash -- "$attr" "$outfile" )"
                [[ -n "$diff" ]] && {
                    echo "${pkg}: ${diff}" >> "$GITHUB_OUTPUT"
                }
              done

              echo "WHEREDOC" >> "$GITHUB_OUTPUT"


        - name: Open PR
          uses: peter-evans/create-pull-request@v6
          with:
            add-paths: "packages"
            title: "sources: update [bot]"
            commit-message: "sources: update [bot]"
            body: |
                ## nvfetcher results
                ${{ steps.nvfetcher_results.outputs.content }}

                ## vendorHash updates
                ${{ steps.update_vendorhashes.outputs.content }}
