name: "Update sources"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 6 * * 1"

jobs:

    update-sources:

        runs-on: ubuntu-latest

        defaults:
            run: { shell: bash }

        steps:

        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup nix
          uses: MidAutumnMoon/spheti-action/nix@master
          with:
            cachix-url: "https://nuirrce.cachix.org/"
            cachix-pubkey: "nuirrce.cachix.org-1:KQWa6ZfDkMPXeDiUpmyDhNw4CmgybPyeVklmi/1Rtqk="

        - name: Install required tools
          run: |
            # empty

        - name: Run nvfetcher
          run: |
            fish "packages/__script/nvfetcher.fish" \
                "packages/sources.toml" \
                "${{ github.token }}" \
            | tee "/tmp/nvfetcher_outputs"
            # strip outputs
            sed --in-place '0,/^Changes/d' "/tmp/nvfetcher_outputs"

        # The holyf Bash will hunt you to death and burn your house to ash
        # if you'd dare to do something with the mf multiline string
        - name: Read nvfetcher outputs so that we can have a nice PR
          id: nvfetcher_outputs
          uses: juliangruber/read-file-action@v1
          with: { path: "/tmp/nvfetcher_outputs" }

        - name: Open PR
          uses: peter-evans/create-pull-request@v5
          with:
            add-paths: "packages"
            delete-branch: true
            title: "sources: update [bot]"
            commit-message: "sources: update [bot]"
            committer: "GitHub <noreply@github.com>"
            author: "GitHub <noreply@github.com>"
            body: ${{ steps.nvfetcher_outputs.outputs.content }}
