name: "Update sources"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 6 * * 1"

jobs:

    update-sources:

        runs-on: ubuntu-latest

        defaults:
            run: { shell: bash }

        steps:

        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Setup nix
            uses: MidAutumnMoon/spheti-action/nix@master
            with:
                cachix-url: "https://nuirrce.cachix.org/"
                cachix-pubkey: "nuirrce.cachix.org-1:KQWa6ZfDkMPXeDiUpmyDhNw4CmgybPyeVklmi/1Rtqk="

        -   name: Update flakes
            run: |
                nix flake update

        -   name: Run nix-update
            id: nix_update
            run: |
                # idiot bash (eye roll)
                declare -r REPORT="$( mktemp )"
                nix run .#nuranScripts.nix-update-driver "$REPORT"
                { echo "REPORT<<EOF"; cat "$REPORT"; echo "EOF"; } >> "$GITHUB_OUTPUT"

        -   name: Open PR
            uses: peter-evans/create-pull-request@v7
            with:
                sign-commits: true
                add-paths: "packages"
                title: "sources: update [bot]"
                commit-message: "sources: update [bot]"
                body: |
                    ${{ steps.nix_update.outputs.REPORT }}
