name: "Update sources"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 6 * * 1"
    push:
        paths:
        - "flake.*"

jobs:

    update-sources:

        runs-on: ubuntu-latest

        defaults:
            run: { shell: bash }

        steps:

        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Setup nix
            uses: MidAutumnMoon/spheti-action/nix@master
            with:
                cachix-url: "https://nuirrce.cachix.org/"
                cachix-pubkey: "nuirrce.cachix.org-1:KQWa6ZfDkMPXeDiUpmyDhNw4CmgybPyeVklmi/1Rtqk="

        -   name: Run nix-update
            id: nix_update
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                # idiot bash (eye roll)
                declare -r REPORT="$( mktemp )"
                nix run .#nuranScripts.nix-update-driver "packages/update.rb" "$REPORT"
                { echo "REPORT<<EOF"; cat "$REPORT"; echo "EOF"; } >> "$GITHUB_OUTPUT"

        -   name: Get Date
            run: |
                echo "THE_DATE=$( date '+%Y/%b/%d' )" >> "$GITHUB_ENV"

        -   name: Open PR
            uses: peter-evans/create-pull-request@v7
            with:
                sign-commits: true
                add-paths: "packages"
                title: "pkgs: update ${{ env.THE_DATE }}"
                body: ${{ steps.nix_update.outputs.REPORT }}
                commit-message: |
                    pkgs: update ${{ env.THE_DATE }}

                    ${{ steps.nix_update.outputs.REPORT }}
