name: "Build custom Caddy"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 */7 * *"

jobs:

    update-sources:

        runs-on: ubuntu-latest

        defaults:
            run: { shell: bash }

        env:
            HASH_METHOD: xxh64sum
            OUTPUT_CADDY: caddy

        steps:

        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup nix
          uses: MidAutumnMoon/spheti-action/nix@master

        - name: Install tools
          run: |
            nix profile install nixpkgs#{fish,xxHash,jq,xcaddy}
            # Create shims for xxhash
            sudo ln -s "$(which xxhsum)" "/usr/local/bin/$HASH_METHOD"

        - name: Build with xcaddy
          id: xcaddy-build
          # outputs:
          # - "caddy_version": version of the targeted caddy
          run: |
            fish packages/__scripts/xcaddy-build.fish

        - name: Hash
          id: caddy-hash
          # outputs:
          # - "caddy_hash": $HASH_METHOD of the built caddy
          run: |
            hash="$( $HASH_METHOD $OUTPUT_CADDY | awk '{print $1}' )"
            echo "caddy_hash=$hash" >> "$GITHUB_OUTPUT"

        - name: Try
          run: |
            echo "${{ steps.xcaddy-build.outputs.caddy_version }}"
            echo "${{ steps.caddy-hash.outputs.caddy_hash }}"
